<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * PageStudio
 *
 * A web application for managing website content. For use with PHP 5.4+
 * 
 * This application is based on the PHP framework, 
 * PIP http://gilbitron.github.io/PIP/. PIP has been greatly altered to 
 * work for the purposes of our development team. Additional resources 
 * and concepts have been borrowed from CodeIgniter,
 * http://codeigniter.com for further improvement and reliability. 
 *
 * @package     PageStudio
 * @author      Cosmo Mathieu <cosmo@cimwebdesigns.com>   
 */
 
// ------------------------------------------------------------------------

class Calendar_model extends Model 
{	
    /**
     * Array to hold errors generated by this object
     * @var     array 
     */
    private $errors = array();
    
	public function __construct()  
    {  

    } 
    
    /**
     * Get all calendar events from the database
     * 
     * @param      
     * @return     object|false
     */ 
    public function getEvents()
	{
        $query = Database::getInstance()->query("SELECT * FROM cimp_calendar");

        if( ! $query->count()) {
            //echo 'No record found';
        } else {            
            return $query->results();
        }
        
	}
    
    // --------------------------------------------------------------------  
	
    /**
     * Return the details for the queried event
     *
     * @param      array $ID Event entry ID
     * @return     object
     */
	public static function getEvent($ID)
	{
		$query = Database::getInstance()->query(
            "SELECT * FROM cimp_calendar WHERE id = ?", array(escape_and_addslashes( $ID ))
        );

        if( ! $query->count()) {
            //echo 'No record found';
        } else {            
            return $query->results();
        }
	}
    
    // --------------------------------------------------------------------  
    
    /**
     * Creates and entry in the database 
     *
     * @param      string $table  
     * @param      array $fields Array of table key and value
     * @return     bool true or false
     */
	public function create($table, $fields, $slider_author)
	{
		$query = Database::getInstance()->insert(
            $table, $fields
        );
        
        return ( ! $query) ? true : false;
	}
    
    // --------------------------------------------------------------------  
       
    /**
     * Updates a specific entry in the database
     *
     * @param      int $ID
     * @param      array $array
     * @return     bool
     */
	public function update($ID, $array = array())
	{
		$query = Database::getInstance()->update(
            "cimp_calendar", $ID, $array
        );
        
        return ( ! $query) ? false : true;
	}

    // --------------------------------------------------------------------  
    
    /**
     * Delete event from the database
     * 
     * @access     Public
     * @param      int $ID Slider ID
     * @return     bool true|false 
     */
    public function delete($ID) 
    {
        $query = Database::getInstance()->delete(
            'cimp_calendar', array('id', '=', $ID)
        );
        
        // Log errors if any
        if( ! $query) {
            $this->errors[] = 'The query to delete event (' . $ID . ') failed!';
            log_message('E_USER_ERROR', 'The query to delete event (' . $ID . ') failed!', __FILE__, __LINE__);
            return false;
        } else {
            return true;
        }
    }
    
}

/* End of file calendar_model.php */
/* Location: ./application/modules/calendar/models/calendar_model.php */